### ISSUE TITLE
Released image on Dockerhub is very out-of-date

### ISSUE THREAD

**Issue by apetresc** [djmaze/apprise-microservice#4]
I was trying to use the newly-added `NOTIFICATION_URLS_FILE` feature, only to realize the image pushed to [hub.docker.com](//hub.docker.com) is almost two years old and doesn't include that feature at all. Could we get a new release tagged and pushed so we don't have to maintain a fork in our own repository?

Thanks! 🙂

**Comment by djmaze** [comment]
Sorry for the neglection of this project. I just updated the build process and made sure the`latest` image contains the latest changes. Also, there are (semantically) tagged images and I recommended using the `0.2.0` or `0.2` in order to have a stable version.

**Comment by apetresc** [comment]
Awesome, thank you :) Better late than never!
